### ISSUE TITLE
Use Kind for e2e tests

### ISSUE THREAD

**Issue by johscheuer** [inovex/illuminatio#28]
Currently kind doesn't support CNI (at leas you can't bring your own CNI -> https://github.com/kubernetes-sigs/kind/issues/273) as soon as this feature is available we should use kind instead of the custom setup in the e2e tests.

**Comment by BenTheElder** [comment]
👋 CNI for the "node" containers, or CNI at the cluster level between the pods running on the "nodes"?

The latter is supported, you can set the following config:
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  disableDefaultCNI: true
```
and install your own CNI

**Comment by johscheuer** [comment]
Hi,

I meant the latter, so that we can create kind clusters with different CNI Networks for our testing setup. Awesome that it's supported now I will take a look at it !

Thanks for taking time and tell us :)

**Comment by johscheuer** [comment]
Since we are (more or less) happy with the dockerized with minikube setup I would close this issue since Kind doesn't support different container runtimes.
