### ISSUE TITLE
Better Result format

### ISSUE THREAD

**Issue by johscheuer** [inovex/illuminatio#44]
During investigating into https://github.com/inovex/illuminatio/issues/29 I stumbled over the following "issue": The results format of the ConfigMap of the illuminatio runner is not really nice to use in an programmatic way (you need to parse string..). The current format lookslike the following:

```yaml
apiVersion: v1
items:
- apiVersion: v1
  data:
    results: |
      01-deny-all:web-7d65dd8bf4-kn6hz:
        01-deny-all:web:
          '-80': {nmap-state: filtered, string: 'Test 01-deny-all:web:-80 succeeded

              Couldn''t reach 01-deny-all:web on port 80. Expected target to not be reachable',
            success: true}
    runtimes: |
      tests:
        01-deny-all:web-7d65dd8bf4-kn6hz: {'01-deny-all:web': 2.1348140239715576}
  kind: ConfigMap
  metadata:
    creationTimestamp: "2019-08-19T13:40:50Z"
    labels:
      illuminatio-cleanup: always
      illuminatio/runner: result
    name: illuminatio-runner-mrw7l-results
    namespace: illuminatio
    resourceVersion: "7756"
    selfLink: /api/v1/namespaces/illuminatio/configmaps/illuminatio-runner-mrw7l-results
    uid: 754ac8bb-d415-40ad-bf2e-6b1e525daeb8
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

I would propose another results format (assume that the content below will be part of the ConfigMap data):

```yaml
Runner: 01-deny-all:web-7d65dd8bf4-kn6hz
Results:
- "01-deny-all:web":
    - "name": "-80": 
      "description": "Expected target to not be reachable ..."
      "result": "success"
      "runtime": "..."
```

@maxbischoff @hacker-h what is your opinion?

**Comment by hacker-h** [comment]
I am uncertain whether this would really be a big improvement.
In the lines 320 and 332 of the `test_orchestrator.py` the results field is treated as a casual yaml string.
However I aggree that your suggestion is more beautiful, but I would not set high priority on this change.
