### ISSUE TITLE
Build internal cache for targeted namespaces

### ISSUE THREAD

**Issue by hacker-h** [inovex/illuminatio#60]
Regarding the implementation of the test_orchestrator functions e.g. `_create_project_namespace_if_missing` we should build an internal cache containing all namespaces to work on to increase the performance.

**Comment by johscheuer** [comment]
illuminatio has already an internal cache for namespaces: https://github.com/inovex/illuminatio/blob/master/src/illuminatio/test_orchestrator.py#L72
