### ISSUE TITLE
Implement running tests from test config

### ISSUE THREAD

**Issue by maxbischoff** [inovex/illuminatio#90]
It would be nice to be able to supply test cases that are run by illuminatio. This could be implemented as a `--test-cases` cmd flag accepting a path to a file, that would cause test case generation to be skipped. In https://github.com/inovex/illuminatio/blob/master/src/illuminatio/illuminatio.py#L79 instead of generating test cases, the file could then be passed if the flag is set.

**Comment by johscheuer** [comment]
I think there are two things that could also be solved here:

-  Rerun the tests without the test generation 
- Allow to provide a custom test file (without test generation)

In the end IMHO: the can be simplified into the following to steps (which can be run independently):

1. Generate tests cases and create a ConfigMap (or upload an existing test cases file)
2. Run the tests defined in the ConfigMap

This would allow users to generate the basic tests and then add or modify these tests (if wanted).
